### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by jensbodal**

### CODE REVIEW

**Comment by catamphetamine** [comment]
Why do you think it's MIT?
It's not MIT.
Closing.
See the licence section of the readme.

**Comment by jensbodal** [comment]
Did not see that section in the README -- my apologies. I assumed since https://github.com/catamphetamine/react-phone-number-input is MIT licensed and installs this package then this one would be as well. It would appear https://github.com/catamphetamine/react-phone-number-input would have fallen under the same restrictions as this package as it used to export this one as a submodule.

**Comment by catamphetamine** [comment]
> It would appear https://github.com/catamphetamine/react-phone-number-input is not actually compatible with the MIT license since it includes these same flag icons.

Well, that depends on how you look at it.
`react-phone-number-input` allows specifying `flagUrl` property, and the default `flagUrl` points to `country-flag-icons` which happens to be not MIT-licenced.
But `flagUrl` property could be changed to point at any country flag icons (theoretically having any aspect ratio), so that part doesn't invalidate its MIT licence.

Also, `react-phone-number-input` uses `country-flag-icons` as its `/flags` export:

```js
export { default as default } from 'country-flag-icons/react/3x2'
```

But, again, if `react-phone-number-input/flags` aren't imported in an app then that code doesn't get included in the bundle, so again its MIT licence is not invalidated.

So, to conclude, `country-flag-icons` can be easily swapped with something else by a developer if required, and there will be no traces of it in the final app in that case.
For example, there's [`FlagKit`](https://github.com/catamphetamine/country-flag-icons#alternatives), accessible via [`flagpack`](https://flag.pk) library.
Currently, they don't have a couple of flags.
I've submitted a pull request to `flagpack` repo:
https://github.com/jackiboy/flagpack/pull/4
The issue: https://github.com/jackiboy/flagpack/issues/3
You can leave a comment there if you want.
If they merge it, then it could be used in place for `country-flag-icons`:

```css
:root {
  --PhoneInputCountryFlag-aspectRatio: 1.333;
}
```

```js
<PhoneInput flagUrl="https://flag.pk/flags/4x3/{xx}.svg" .../>
```

I have updated the flags readme section:
https://github.com/catamphetamine/react-phone-number-input#flags
And released a new version of the library that supports `--PhoneInputCountryFlag-aspectRatio`.

**Comment by jensbodal** [comment]
Great thanks for all the info. I'll see what I end up doing.

**Pull request closed without merging**
